---
# tasks file for deploy_web
    - name: Linux
      debug: var=ansible_os_family

    - block: #---------RedHat--------
      - name: Install Web Server for RedHat
        yum: name=httpd state=latest

      - name: Start Web Server for RedHat
        service: name=httpd state=restarted enabled=yes
      when: ansible_os_family == "RedHat"

    - block: #---------Debian--------
      - name: Install Web Server for Debian
        apt: name=apache2 state=latest

      - name: Start Web Server for Debian
        service: name=apache2 state=restarted enabled=yes
      when: ansible_os_family == "Debian"

    - name: Create folder image
      file:
        path: "{{ dest_folder }}/img"
        state: directory
        mode: 0755

    - name: Create folder style
      file:
        path: "{{ dest_folder }}/style"
        state: directory
        mode: 0755

    - name: Copy img
      copy:
        src: "item"
        dest: "{{ dest_folder }}"
        mode: 0555
      loop:
        - "photo.jpg"
      notify:
        - Restart Debian
        - Restart RedHat

    - name: Copy style
      copy:
        src: "item"
        dest: "{{ dest_folder }}"
        mode: 0555
      loop:
        - "styles.css"
        - "reset.css"
      notify:
        - Restart Debian
        - Restart RedHat

    - name: Generate index
      template:
        src: "index.j2"
        dest: "{{ dest_folder }}/index.html"
        mode: 0555
      notify:
        - Restart Debian
        - Restart RedHat
