---
# handlers file for deploy_web
- name: Restart RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
